import math

# Generated by chatgpt based on this ascii art:
#      c
#     /
#    /
#   /
#  O
#  |
#  |
#  O
#  R

def forward_kinematics(theta1, theta2, theta3, L1, L2, L3):
    x = (L2 * math.cos(theta1)) + (L3 * math.cos(theta1 + theta2 + theta3))
    y = (L2 * math.sin(theta1)) + (L3 * math.sin(theta1 + theta2 + theta3))
    z = L1
    return x, y, z


# Example usage:
theta1 = math.radians(0)  # Convert to radians if necessary
theta2 = math.radians(0)  # Convert to radians if necessary
theta3 = math.radians(0)  # Convert to radians if necessary
L1 = 2  # Length from R to O
L2 = 3  # Length from O to c
L3 = 0  # Since there's zero length between c and end effector

x, y, z = forward_kinematics(theta1, theta2, theta3, L1, L2, L3)
print(f"x: {x}, y: {y}, z: {z}")
